### ISSUE TITLE
[Bug] Sourcemap is likely to be incorrect: a plugin (@analogjs/vite-plugin-angular)

### ISSUE THREAD

**Issue by sand4rt** [sand4rt/playwright-ct-angular#6]
When building Playwright component tests i see a lot of sourcemap warnings. See pipeline: https://github.com/sand4rt/playwright-ct-angular/actions/runs/5036859856/jobs/9033313003#step:8:18

related to: https://github.com/analogjs/analog/issues/410

**Comment by brandonroberts** [comment]
This warning should be resolved in version `0.2.27` of the plugin

**Comment by sand4rt** [comment]
@brandonroberts thanks for the reply. I've tried it, but the issue still persists: 
https://github.com/sand4rt/playwright-ct-angular/actions/runs/7221500112/job/19676593078?pr=38#step:8:23
